name: liveyourdream
favicon: null
layout_spectrum: 0.50932
typography_spectrum: 0.90994
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a69b9a'
    - '#7c6456'
    - '#080000'
    - '#f90045'
  brandStrength: 0.25
  lightness: 0.875
  saturation: 0.875
  rhythmicContrast: 1
purpose:
  - name: null
    item: null
    url: null
