analytics: {}
color:
  brandColors:
    - '#A0B8A8'
    - '#000000'
    - '#789090'
    - '#000000'
    - '#000000'
  brandStrength: 0.878471
  lightness: 0.042661
  rhythmicContrast: 0.928609
  saturation: 0.625
cta: {}
layout_spectrum: 0.984797
name: livingabundantly
opengraph: {}
purpose: {}
typography_spectrum: 0.138513
