analytics: {}
color:
  brandColors:
    - '#A0B8A8'
    - '#000000'
    - '#789090'
    - '#000000'
    - '#000000'
  brandStrength: 0.337837
  lightness: 0.79054
  rhythmicContrast: 0.83277
  saturation: 0.77027
cta: {}
layout_spectrum: 0.190878
name: liveyourdream
opengraph: {}
purpose: {}
typography_spectrum: 0.138513
