name: liveyourdream
favicon: null
layout_spectrum: 0.93182
typography_spectrum: 0.66562
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b4a399'
    - '#3d3f6f'
    - '#d72c8a'
    - '#871644'
  brandStrength: 0.375
  lightness: 0.875
  saturation: 0.875
  rhythmicContrast: 0.75
purpose:
  - name: null
    item: null
    url: null
