name: liveyourdream
favicon: null
layout_spectrum: 0.51198
typography_spectrum: 0.18108
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#edc9a5'
    - '#7c6150'
    - '#000000'
    - '#fd2955'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose:
  - name: null
    item: null
    url: null
