analytics: {}
color:
  brandColors:
    - '#000000'
    - '#501010'
    - '#000000'
    - '#A84038'
    - '#E8C880'
  brandStrength: 0.878471
  lightness: 0.042661
  rhythmicContrast: 0.928609
  saturation: 0.625
cta: {}
layout_spectrum: 0.984797
name: liveyourdream
opengraph: {}
purpose: {}
typography_spectrum: 0.138513
